name: stylegan3
channels:
  - pytorch
  - nvidia
dependencies:
  - python >= 3.8
  - pip
  - numpy>=1.25
  - click>=8.0
  - pillow=9.4.0
  - scipy=1.11.0
  - pytorch>=2.0.1
  - torchvision>=0.15.2
  - cudatoolkit=11.1
  - requests=2.26.0
  - tqdm=4.62.2
  - ninja=1.10.2
  - matplotlib=3.4.2
  - imageio=2.9.0
  - pip:
    - imgui==2.0.0
    - glfw==2.6.1
    - gradio==3.35.2
    - pyopengl==3.1.5
    - imageio-ffmpeg==0.4.3
    # pyspng is currently broken on MacOS (see https://github.com/nurpax/pyspng/pull/6 for instance)
    - pyspng-seunglab




Traceback (most recent call last):
  File "/xxx/dl/apps/DragGAN/PTI/run.py", line 24, in <module>
    raise e
  File "/xxx/dl/apps/DragGAN/PTI/run.py", line 21, in <module>
    align_data.pre_process_images(image_original)
  File "/xxx/dl/apps/DragGAN/PTI/utils/align_data.py", line 24, in pre_process_images
    raise e
  File "/xxx/dl/apps/DragGAN/PTI/utils/align_data.py", line 20, in pre_process_images
    aligned_image = align_face(filepath=f'{raw_images_path}/{image_name}',
  File "/xxx/dl/apps/DragGAN/PTI/utils/alignment.py", line 35, in align_face
    lm = get_landmark(filepath, predictor)
  File "/xxx/dl/apps/DragGAN/PTI/utils/alignment.py", line 15, in get_landmark
    img = dlib.load_rgb_image(filepath)
RuntimeError: Unable to open file: ./image_original/09Hunter1-superJumbo.jpeg